title = "LORENZO PIROLA"
baseURL = "https://lpirola13.github.io"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Lorenzo Pirola"
  description = "Computer Science master's degree student at Università degli Studi di Milano Bicocca"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "Made with Hugo - inspired by Olivier Roques' theme. Last update September 28th, 2021"
    url = "https://github.com/ojroques/hugo-researcher"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "'Source+Code+Pro', sans-serif"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  google_fonts = [
      ["Source+Code+Pro", "300, 400, 600"]
    ]

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "WORK EXPERIENCE"
    url = "#experience"
    weight = 1
  [[menu.main]]
    name = "EDUCATION"
    url = "#education"
    weight = 2
  [[menu.main]]
    name = "PROJECTS"
    url = "#projects"
    weight = 3
  [[menu.main]]
    name = "CONTACTS"
    url = "#contacts"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
